Improve documentation for tf(), step, stepplot, impulse and impulseplot
JuliaControl/ControlSystems.jl pull request #344
Opened 2020-10-05 15:31 UTC by KronosTheLate

In this PR I have changed the following
* changed the documentation for "creating systems" to include an example of using ```s=tf("s")``` syntax
* included the julia> text consistently in the examples under "creating systems"
* removed the #output comment under "creating systems" as I found it un-nessecary, and I don't like the fact that it is not copy-pasted from the REPL, which I think examples should be when possible for maximum clarity
* Clearly stated in the documentation for step, stepplot, impulse and impulseplot what they do
* Fixed a typo in the impulseplot documentation where it said "step" instead of "impulse"

2020-10-05 15:34 UTC, KronosTheLate commented
In regards to what you said @baggepinnen :
> @KronosTheLate, don't forget to base PR:s off the updated master branch of the base package, i.e., pull ControlSystems/master into master on your fork. This way only the commits that are new appear in the PR, and not the commits from your previous PR.

I tried to google how to in multiple different ways, and I also tried to update my personal branch (PR 7), before finally seeing that I could just base this PR off of master. But this PR IS in fact based off of master, just like the last one:
"KronosTheLate wants to merge 11 commits into JuliaControl:master from KronosTheLate:master"

I am not sure how to only make this PR for the new changes, but have simply been wanting to fix this for a week, and I don't want to prioritize finding out how to do it properly, and having it on my mind for more days. I set aside some time now, and I used close to half of it trying to follow your advice. I apologize for my GitHub-illiteracy, I hope you are able to squash it nicely (if you like the changes), and I am very open to step-by-step instructions on how to do it right, or a link to an easy to understand resource.

2020-10-05 16:59 UTC, olof3 requested changes
Thank you for giving some love and care to the docs! (they certainly need it)

2020-10-05 16:59 UTC, olof3 commented on docs/src/man/creating_systems.md
> +
```suggestion
```
This paragraph contributes very little (if any) helpful information.

(OT, the formatting of the coefficients in the transfer functions could be improved)

2020-10-05 16:59 UTC, olof3 commented on docs/src/man/creating_systems.md
> +julia>  tf(zpk([-1], [1], 2, 0.1))
```suggestion
julia> tf(zpk([-1], [1], 2, 0.1))
```

2020-10-05 16:59 UTC, olof3 commented on docs/src/man/creating_systems.md
> +Some times you only have an expression for the transfer-function, and you don't have it reduced to a fraction with polynomials of ```s``` as numerator and denomenator. No problem! The following metho
```suggestion
For more general expressions, it is sometimes convenient to define `s = tf("s")` and then use the variable `s` to define the transfer function.
```

2020-10-05 16:59 UTC, olof3 commented on docs/src/man/creating_systems.md
> +s^2 + 2*s + 1
```suggestion
julia> (s-1)*(s^2 + s + 1)/(s^2 + 3s + 2)/(s+1)

TransferFunction{Continuous,ControlSystems.SisoRational{Int64}}
       s^3 - 1
---------------------
s^3 + 4*s^2 + 5*s + 2
```

Changed to a non-trivial example that illustrates why this approach would be useful.

2020-10-05 16:59 UTC, olof3 commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
The statement about that the impulse is called Dirac in one case and Kronecker in the other case doesn't contribute much to the understanding of the function.

Also, it is not quite the Kronecker delta but 1/Ts * \delta[k]

I absolutely agree that some info about the scaling for discrete-time systems is lacking. Something along the lines of the following is perhaps slightly easier to parse.

```suggestion
For discrete-time systems, the magnitude of the impulse is `1/Ts`.
```

2020-10-05 16:59 UTC, olof3 commented on src/timeresp.jl
> +The step on the input goes from 0 to 1 and occurs at t=0.
This 
```suggestion
Calculate the response of the system `sys` to a unit step at time `t = 0`. If the final time `Tf` or time
vector `t` is not provided, one is calculated based on the system pole
locations.
```

2020-10-05 17:02 UTC, baggepinnen reviewed
Looks good. I just want to double check with @mfalt so that the `#output` syntax is not needed for Documenter.jl doctests?

2020-10-05 17:02 UTC, baggepinnen commented on docs/src/man/creating_systems.md
> +## using the ```tf()``` function
```suggestion
## using the `tf()` function
```

2020-10-05 18:43 UTC, KronosTheLate commented
@olof3 and @baggepinnen thank you so much for the thorough feedback, much appriciated. First time adding real documentation, so pointers are very much appriciated. Ill look through it properly tomorrow, but from what I can tell now I will add all the suggestions 😃

2020-10-05 22:47 UTC, mfalt commented
> Looks good. I just want to double check with @mfalt so that the `#output` syntax is not needed for Documenter.jl doctests?

I don't think those are working properly currently anyway.  When I have time to fix https://github.com/JuliaControl/ControlSystems.jl/pull/293 I'll check if I need to re-add them, but I see no need to delay this PR.

I think some of the wording could be improved, but I guess it is better to have some documentation than none.

2020-10-06 14:03 UTC, KronosTheLate commented on docs/src/man/creating_systems.md
> +
Agreed, this can be removed to keep the docs clear and concise, in particular with respect to the doc's job of documenting the functions, and not really anything else

2020-10-06 14:04 UTC, KronosTheLate commented on docs/src/man/creating_systems.md
> +Some times you only have an expression for the transfer-function, and you don't have it reduced to a fraction with polynomials of ```s``` as numerator and denomenator. No problem! The following metho
I like this rephrasing a lot. I would like to merge it, but it says "outdated" so that I can't, and I am not sure how to fix that. Should I request the same change again myself, and approve it?

2020-10-06 14:14 UTC, KronosTheLate commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
I agree that my formulation is not great. But I would not understand the impulse as well as I currently do with your suggestion, and I like understanding it more than your suggestion would tell me.

Here are two replacements I am happy with, where I prefer the first one:
"The impulse is such that the area under it is 1, with the shortest possible time-step."
I find this formulation extremely clear, consise and general for both discrete and continuous systems.

"For continuous systems the impulse is the Dirac delta function. 
For discrete functions, the impulse has width `Ts` and magnitude `1/Ts`."
I find this explanation detailed, yet short and easy to understand.
Maybe magnitude should be height, as it is more descriptive because it is positive.

Ofc feel free to rephrase it if you don't like the two options I am happy with ^_^

2020-10-06 14:30 UTC, KronosTheLate commented on docs/src/man/creating_systems.md
> +Some times you only have an expression for the transfer-function, and you don't have it reduced to a fraction with polynomials of ```s``` as numerator and denomenator. No problem! The following metho
I made the change manually in a new commit, hope that is fine

2020-10-06 14:49 UTC, KronosTheLate commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
I have been making a mess in a couple of commits just now, but I have made some consistensy and capitilization changes, and I also went ahead and changed the docs for impulse to my first and favourite suggestion. Ofc, that is not because this is settled, but because I had messed it up, and in fixing it I just applied the change. Still waiting to hear your opinion before changing docs for impulseplot to the same wording

2020-10-07 10:15 UTC, olof3 commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
Discrete-time signals are just sequences of numbers. It is clear that a discrete-time impulse is just [a_0, 0, 0, ....].
There are no such things as area or width of discrete-time impulses, so your suggestions are a bit problematic, and I would prefer my suggestion.

The way that Matlab (and this toolbox) plots discrete-time time-responses is technically incorrect, and is probably why you would like a different formulation?

@mfalt @baggepinnen We should at least have an option for stem plots for discrete-time time responses, but I think it is better if the current approach is the default, otherwise there will be a lot of clutter.

2020-10-07 10:51 UTC, baggepinnen commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
- The user can always supply `seriesstyle = :stem` (or `:sticks` or whatever the keyword is) if we have not forced `:step`. 
- I think with "area equal to 1" it's ment that under a ZoH assumption, the area of the impulse will be 1. We do not really have many facilities to handle different forms of discretizations in the toolbox, other than `c2d` performing ZoH-sampling.

2020-10-07 11:26 UTC, olof3 commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
> The user can always supply seriesstyle = :stem (or :sticks or whatever the keyword is) if we have not forced :step.

Good to hear!

> I think with "area equal to 1" it's ment that under a ZoH assumption, the area of the impulse will be 1. We do not really have many facilities to handle different forms of discretizations in the toolbox, other than c2d performing ZoH-sampling.

Yes, you can talk about area/width of the ZoH of a discrete-time impulse. But implying that a discrete time-impulse has an area or width simply does not make sense to me. It could be that the discrete-time system represents an inherently discrete process.

2020-10-09 07:25 UTC, KronosTheLate commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
@olof3 After reading your comment a second or third time, I am realizing why my formulation is inaccurate. I am just not used to thing about discrete signals yet, at all. But you are absolutely right.


So how about something like this?

The signal is such that  `timestep * magnitude = 1`. For continuous signals, `timestep → 0`. For discrete signals, `timestep = sampleperiod = Ts`

2020-10-09 11:46 UTC, mfalt commented
@KronosTheLate it is great to see that you want to improve the docs. There is a lot missing, and it is great with input from new users. Most of the maintainers here are more or less PhD students in control, so there is always a risk that we write the documentation in a way that is hard to understand for new users. However, it is also important that the documentation is fairly accurate, so I really appreciate that you are open to discussion and input.

I will try to add and rewrite significant parts of the documentation of the package, over the weekend if I find the time. Any input on the new documentation would be very helpful.
The changes in this PR will of course also be pulled in some way.

2020-10-11 11:02 UTC, olof3 commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
I think you are right that we should describe what sort of impulses that we are talking about, even if it should be quite obvious. How about the following,


```suggestion
The response to
* A unit Dirac impulse at time `t=0` (continuous-time systems)
* An impulse with magnitude `1/Ts` at time `k=0` (discrete-time systems)
```

2020-10-11 11:33 UTC, KronosTheLate commented
> @KronosTheLate it is great to see that you want to improve the docs. There is a lot missing, and it is great with input from new users. Most of the maintainers here are more or less PhDs in control, so there is always a risk that we write the documentation in a way that is hard to understand for new users. However, it is also important that the documentation is fairly accurate, so I really appreciate that you are open to discussion and input.
> 
> I will try to add and rewrite significant parts of the documentation of the package, over the weekend if I find the time. Any input on the new documentation would be very helpful.
> The changes in this PR will of course also be pulled in some way.

I appreciate being heard by people who know a lot more than me ^_^ I have to make clear, I did not know what a transfer-function was a couple of months ago. I am just going to start looking at actually preforming any control of a system (we have only looked at closed loops without a propper actuator, I believe). I am SO green on this subject. But I am also psyched that there is a Julia-package than can do basically everything we are doing in MatLab, allowing independence from the MatLab license. I am so grateful for the work you guys have put into this, making Julia a viable option :D

I will be honoured to make a can-I-understand-this review on your improvements to the docs. I am scared that I might not know what we are talking about at some point, not because of the phrasing, but because I don't have a clue. And as the docs are not to educate people on relevant theory, I might be clueless at some points. But I'll do my best ^_^

2020-10-19 14:44 UTC, KronosTheLate commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
I have been waiting for your reply for the last 10 days, only to see you made it 8 days ago. Whoopsie

I like it a lot. My only problem is the formulation "at time `k=0`". I am in this deep enough that I am committing to the documentation, but I still don't know the variable k. Nor am I able to find it as an argument to the function. Why not call it t, if it is just some arbitrary time? I would personally find it less confusing that way.

2020-10-19 14:48 UTC, KronosTheLate commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
> even if it should be quite obvious.

As a newbie, I had NO idea what to expect a short while ago. Nothing was obvious (Picture confused student in a new course - certain about just about nothing in the new subject). Maybe a step function is something obvious, but no fancy math like a Dirac delta function. So I really like that we are making the documentation navigatable to someone who is just learning about this, and try to use Julia for it ^_^

2020-10-19 16:39 UTC, olof3 commented on src/timeresp.jl
> +For discrete systems this is the Kronecker delta function.
> I have been waiting for your reply for the last 10 days, only to see you made it 8 days ago. Whoopsie
> 
> I like it a lot. My only problem is the formulation "at time `k=0`". I am in this deep enough that I am committing to the documentation, but I still don't know the variable k. Nor am I able to find it as an argument to the function. Why not call it t, if it is just some arbitrary time? I would personally find it less confusing that way.

I see the same problem as you do, however, it it the terminology and notation used in "Computer Controlled systems", which the toolbox is aligned with to a large extent. I find it quite weird to denote discrete time with `t`. I was debating whether it should be "sample instant `k`", but went with time in accordance with (Computer Controlled Systems), it is quite clear from the context. To me the proposal seems sufficiently consistent with the literature.

@baggepinnen @mfalt we should have some document where we try to document the preferred terminology and notation to improve the consistency in the documentation. Also, any opinions for this particular case?

> As a newbie, I had NO idea what to expect a short while ago. Nothing was obvious (Picture confused student in a new course - certain about just about nothing in the new subject). Maybe a step function is something obvious, but no fancy math like a Dirac delta function. So I really like that we are making the documentation navigatable to someone who is just learning about this, and try to use Julia for it ^_^

Some things are better explained in textbooks, but a little bit of extra clarity in the docs doesn't hurt.

2020-10-29 16:50 UTC, KronosTheLate commented
I have struggled a little with taking in reviews, having them become outdated, and some conflicts. But I _think_ that it should be all good now, so as far as I know, this PR is ready for merge.

2021-06-03 12:06 UTC, KronosTheLate commented
So, this PR seems to have gotten outdated. Are the points adressed by it fixed, or should the changes be copied into another PR based of the current master branch?

2023-10-10 13:46 UTC, closed without merging

2023-10-10 13:52 UTC, KronosTheLate commented
Closed in favor of https://github.com/JuliaControl/ControlSystems.jl/pull/881