Add function to order conjugate pairs in zpk constructor
JuliaControl/ControlSystems.jl pull request #386
Opened 2020-10-30 11:39 UTC by albheim

Add `order_conjugates!` to pair up and order poles/zeros in the order LAPACK uses (positive imaginary part first followed by conjugate) and call it in constructor for SisoZpk type if there are complex poles/zeros.

Ordering only cares about pairing up exact conjugates and putting them in the desired order, and leaves other things as it is. It also skips a complex number if there is no conjugate, which will then be caught by `check_real` which is called right after. 

From #369 I though that there could be numerical problems that forced us to assume conjugates might not match perfectly, but I believe after discussing with @mfalt that this was a misunderstanding from my side and that we can assume the correct conjugate always exists exactly in our internal transformations. And assuming that the user supplies exact conjugates is reasonable to me so I implemented this under the assumption that there will be exact matches, else it will error in `check_real`.

2020-10-30 11:43 UTC, albheim commented on src/types/SisoTfTypes/SisoZpk.jl
>              @assert check_real(p) "zpk model should be real-valued, but poles do not come in conjugate pairs."
I believe `check_real` is only used here so maybe it would be nicer to just make that check when ordering them?

2020-10-30 11:46 UTC, albheim commented
I found some weird behavior I didn't understand in https://github.com/JuliaControl/ControlSystems.jl/blob/311013eef4dd3384872abfca1c04dabb213c97ed/src/types/zpk.jl#L37 which seems to call the SisoZpk constructor twice. Not really connected to this, but thought I would just ask if anyone had a clue why this would be? The type created is exactly the same as the one the array has, so no conversion or anything should be needed?

2020-10-30 11:47 UTC, albheim commented on src/types/SisoTfTypes/SisoZpk.jl
> +function order_conjugates!(x)
Currently it modifies the vectors which maybe is not very good since the constructor does not have bang notation? Not sure what the convention is there.

2020-10-30 20:09 UTC, mfalt requested changes

2020-10-30 20:09 UTC, mfalt commented on src/types/SisoTfTypes/SisoZpk.jl
> +function order_conjugates!(x)
We generally let the inputs be references to the user inputted arrays, with the implicit implication that the user might screw things up of they change the vectors afterwards. But I agree, we should probably do a copy here.

2020-10-30 20:09 UTC, mfalt commented on src/types/SisoTfTypes/SisoZpk.jl
>              @assert check_real(p) "zpk model should be real-valued, but poles do not come in conjugate pairs."
I think it's better to be explicit. But the name of check_real could probably be improved. (I don't think it's necessary to change for this PR)

2020-10-31 09:22 UTC, olof3 commented on src/types/SisoTfTypes/SisoZpk.jl
>              @assert check_real(p) "zpk model should be real-valued, but poles do not come in conjugate pairs."
Yes, i think the check should be done when "ordering" them, but I think it would be better to call the function something like `matchup_conjugates`, or `pairup_conjugates`. Whlie it currently does order them, I'd say that the main task is to pair them up. If the name is changed to something like this, it is natural that it throws an error if there is a conjugate that can't be paired up.

2020-10-31 10:12 UTC, olof3 commented
Great that you're looking into this. This PR definitely addresses the problem that you discovered in that other issue.

I think it could be a good time to think about if the current way is the way we would like to do things (although, I'm quite happy with the current approach). 

* (current approach) Ensure that conjugates come after each other, with the conjugate with positive imaginary part first. This could be a problem for symbolic variables, but this is my only concern. Not sure how much effort or how realistic it is to achieve even half-reasonable support for this?
* Ensure that the conjugates come after each other, but don't worry about which comes first. This doesn't make it any harder to convert to transfer functions, but gives a slightly less ordered impression.
* Just check that the conjugates match up. Then there will be a little bit of more work when converting to a transfer function, but I believe that the impact is primarily there (and an even less orderly print).

2020-11-02 12:37 UTC, albheim commented
> I found some weird behavior I didn't understand in
> 
> https://github.com/JuliaControl/ControlSystems.jl/blob/311013eef4dd3384872abfca1c04dabb213c97ed/src/types/zpk.jl#L37
> 
> which seems to call the SisoZpk constructor twice. Not really connected to this, but thought I would just ask if anyone had a clue why this would be? The type created is exactly the same as the one the array has, so no conversion or anything should be needed?

I created a specific issue for this after talking with @mfalt, see #387

2020-11-02 12:57 UTC, albheim commented
> I think it could be a good time to think about if the current way is the way we would like to do things (although, I'm quite happy with the current approach).

I also think the current approach works well enough. It does not take much time to pair up the roots, and especially if they are already paired it is basically a single for loop over the roots. It makes for easier/nicer printing which I feel is nice.

Now I only did pair up the roots since that is what crashed the code some times, but I was also wondering if the roots from LAPACK were sorted according to any additional criteria, have not tried to look this up myself. Anyone of you know this?

2020-11-02 13:49 UTC, olof3 commented
> I was also wondering if the roots from LAPACK were sorted according to any additional criteria, have not tried to look this up myself. Anyone of you know this?

From what I've seen, the only guarantee is that they are only paired up, with the one with positive real imaginary part first. Not 100% sure though.

2020-11-02 16:38 UTC, albheim commented on src/types/SisoTfTypes/SisoZpk.jl
>              @assert check_real(p) "zpk model should be real-valued, but poles do not come in conjugate pairs."
I changed the name to `pairup_conjugates` and also implemented a check in the pairing loop. For me it is either way with the `check_real`, I feel it is a bit unnecessary to loop through the poles twice, but that probably is a very small fraction of the time so if you think the code is clearer with it I can go with that.

2020-11-02 16:39 UTC, albheim commented on src/types/SisoTfTypes/SisoZpk.jl
> +function order_conjugates!(x)
I added `z, p = copy(z), copy(p)` in the case where we reorder the vectors.

2020-11-02 19:29 UTC, olof3 reviewed
The idea looks alright, some minor suggestions for readability.

2020-11-02 19:29 UTC, olof3 commented on src/types/SisoTfTypes/SisoZpk.jl
> +    by the LAPACK routines that return complex-conjugated values, i.e., (x+iy) is followed by (x-iy)"""
```suggestion
"""Reorder the vector x of complex numbers so that complex conjugates come after each other, with the one with positive imaginary part first. Returns true if the conjugates can be paired and otherwise false."""
```
Good with a comment, but what is TR and T? Also, might not necessarily be poles.

2020-11-02 19:29 UTC, olof3 commented on src/types/SisoTfTypes/SisoZpk.jl
> +function pairup_conjugates!(x)
```suggestion
function pairup_conjugates!(x::AbstractVector)
```

2020-11-02 19:29 UTC, olof3 commented on src/types/SisoTfTypes/SisoZpk.jl
> +            @assert pairup_conjugates!(z) "zpk model should be real-valued, but zeros do not come in conjugate pairs."
Should we just let the error be thrown in `pairup_conjugates!` (similarly to in `common_timeevol`), or is this the way we want to go? This way we can let the user know if the problem is with the zeros or the poles. @mfalt

2020-11-02 19:29 UTC, olof3 commented on src/types/SisoTfTypes/SisoZpk.jl
>          end
```suggestion

        # Attempt to find a matching conjugate to x[i]
        j = findnext(==(conj(x[i])), x, i+1)
        j === nothing && return false

        tmp = x[j]
        x[j] = x[i+1]
        # Make sure that the complex number with positive imaginary part comes first
        if imag(x[i]) > 0
            x[i+1] = tmp
        else
            x[i+1] = x[i]
            x[i] = tmp
        end
```
Perhaps a bit more readable in certain respects. Hopefully it works :)

2020-11-02 19:29 UTC, olof3 commented on src/types/SisoTfTypes/SisoZpk.jl
> +        end
```suggestion
```

2020-11-02 19:29 UTC, olof3 commented on test/test_zpk.jl
> +@test zpk([], [1.0+im,1.0,1.0-im], 1.0) == zpk(ComplexF64[], [1.0+im,1.0-im,1.0], 1.0)
One or two more tests would be much appreciated, perhaps with poles that don't match up, and perhaps some double poles.

2020-11-03 23:17 UTC, albheim commented on src/types/SisoTfTypes/SisoZpk.jl
> +            @assert pairup_conjugates!(z) "zpk model should be real-valued, but zeros do not come in conjugate pairs."
Was thinking about it when I did this, I originally wanted to move it to `pairup_conjugates!` which felt like nicer code, but then the error message would not be as informative so I thought this was better after all. But I'm open for suggestions.

2020-11-03 23:23 UTC, albheim commented on src/types/SisoTfTypes/SisoZpk.jl
>          end
Agreed, way nicer.

2020-11-03 23:26 UTC, albheim commented on src/types/SisoTfTypes/SisoZpk.jl
> +    by the LAPACK routines that return complex-conjugated values, i.e., (x+iy) is followed by (x-iy)"""
Yeah, mostly just stole the comment from `checkreal` to have something, but yours is much clearer.

2020-11-03 23:31 UTC, albheim commented on test/test_zpk.jl
> +@test zpk([], [1.0+im,1.0,1.0-im], 1.0) == zpk(ComplexF64[], [1.0+im,1.0-im,1.0], 1.0)
I'll try to fix some more.

2020-11-06 20:26 UTC, mfalt commented
I think it looks good, and i prefer to keep the check in the constructor. It is explicit and clear in the code that this is assumed.

2020-11-07 07:59 UTC, olof3 commented
LGTM

2021-02-01 15:38 UTC, olof3 commented
re-triggered the tests, and it seems like this can be merged

2021-02-01 17:39 UTC, merged