WIP: Update autovec and add more functions
JuliaControl/ControlSystems.jl pull request #388
Opened 2020-11-02 22:47 UTC by albheim

Opened this to start working on adding the additional functions mentioned in #333, also found out about `Core.@__doc__` which is a nicer way of attaching docstrings to macro generated functions than how I was dealing with it so will update that also.

2020-11-04 00:04 UTC, albheim commented on src/freqresp.jl
> +@autovec (1) function freqresp(sys::LTISystem, w_vec::AbstractVector{<:Real})
It seems that adding autovec to freqresp is not as simple as this. The macro assumes that the return value of the function is a tuple and that the index sent in indexes into this tuple. 

We could pretty easily create the special case where we send no index (`@autovec () function ...`) and make that mean to `vec` the entire returned value. This would be rather easy to fix and the only way I can come up with right now. Maybe not the most intuitive, but could okay since it is an internal function?

2020-11-20 14:21 UTC, mfalt requested changes
Is this ready to pull @albheim ? Do we have any remaining functions we should add autovec to?

2020-11-20 14:21 UTC, mfalt commented on src/freqresp.jl
>  Compute the singular values of the frequency response of system `sys` at
```suggestion
Compute the singular values `sv` of the frequency response of system `sys` at
```

2020-11-20 14:47 UTC, albheim commented
> Is this ready to pull @albheim ? Do we have any remaining functions we should add autovec to?

I think I was waiting for feedback on using `@autovec () f()=...` to mean that the entire returned value should be autovecd. So far I only added freqresp, and from #333 we still have numvecv, denvecv, numpolyv and denpolyv. They also seem to be a single returned value so it would be using the same notation in that case.

2020-11-23 18:56 UTC, albheim commented
It was decided that remaining functions from #333 could wait since they introduced some problems in that includes in `ControlSystems.jl` became circular (could rather easily be solved) and that they did not work with how `@autovec` was currently designed. I have some idea of how we could reconstruct `@autovec` to be able to handle more general input instead of integer indices, but I think that will not be a priority for now. 

So with that I think this PR can be considered done.

2021-01-17 05:08 UTC, baggepinnen commented
Mattias requested changes here, but I can't seem to figure out if that has been addressed or not?

2021-01-17 09:17 UTC, albheim commented
> Mattias requested changes here, but I can't seem to figure out if that has been addressed or not?

I don't remember exactly what it was but I believe I fixed what was requested.

2021-01-17 09:24 UTC, baggepinnen commented
I retriggered the tests to make sure, if they pass we'll pull

2021-01-17 10:12 UTC, merged