Field-matching constructors. Fixes #399
JuliaControl/ControlSystems.jl pull request #400
Opened 2020-11-23 04:20 UTC by jonniedie

I just went ahead and made a PR to implement #399 because it was a simple enough change.

2020-11-23 04:27 UTC, baggepinnen requested changes
I'm in favor of this, the lack of those constructors bother me on an almost daily basis. Apart from not accepting invalid sizes, I think it looks good.

2020-11-23 04:27 UTC, baggepinnen commented on src/types/StateSpace.jl
> +StateSpace(A, B, C, D, timeevol, nx, nu, ny) = StateSpace(A, B, C, D, timeevol)
Perhaps a check should be made so that the sizes provided  are consistent with the actual sizes of the matrices? Since the user will now be exposed to these constructors, it makes sense to not accept inconsistent values.

2020-11-23 05:39 UTC, baggepinnen approved these changes

2020-11-23 05:50 UTC, jonniedie commented
Oops, looks like I had a typo in my test

2020-11-23 10:42 UTC, olof3 commented
Shouldn't we just remove the fields and rely on `getproperty` and avoid adding extra code, see #399.

2021-01-17 06:27 UTC, baggepinnen commented
This should be fixed now that we no longer have the extra fields (#411)
I hope it solves your original problem (#399)

2021-01-17 06:27 UTC, closed without merging